CREATE PROC [trans_servicepart_l3_remedy].[gsl_lrt_remedy_ticket_proc] @pipeline_name [VARCHAR](100),@pipeline_run_id [VARCHAR](100),@pipeline_trigger_name [VARCHAR](100),@pipeline_trigger_id [VARCHAR](100),@pipeline_trigger_type [VARCHAR](100),@pipeline_trigger_date_time_utc [DATETIME2] AS
BEGIN TRY
--LOAD-TYPE: Incremental temp2trans
--DECLARE @instance_id varchar(4) = '8702'; @pipeline_trigger_date_time_utc [DATETIME2]
WITH gen_hashkey as (
 SELECT
	NULLIF([f_extract_date_time],'') as [f_extract_date_time],
NULLIF([f_tran_code],'') as [f_tran_code],
NULLIF([f_instance_id],'') as [f_instance_id],
NULLIF([f_remedy_ticket_nbr],'') as [f_remedy_ticket_nbr],
NULLIF([f_alt_ce_part_flag],'') as [f_alt_ce_part_flag],
NULLIF([f_bill_of_lading_desc],'') as [f_bill_of_lading_desc],
NULLIF([f_branch_code],'') as [f_branch_code],
NULLIF([f_carrier_name],'') as [f_carrier_name],
NULLIF([f_ce_part_flag],'') as [f_ce_part_flag],
NULLIF([f_csr_code],'') as [f_csr_code],
NULLIF([f_csr_warehouse_code],'') as [f_csr_warehouse_code],
NULLIF([f_part_source_loc_dist],'') as [f_part_source_loc_dist],
NULLIF([f_closest_invtry_loc_name],'') as [f_closest_invtry_loc_name],
NULLIF([f_country_code],'') as [f_country_code],
NULLIF([f_delivery_method_code],'') as [f_delivery_method_code],
NULLIF([f_msc_carrier_date_time],'') as [f_msc_carrier_date_time],
NULLIF([f_msc_new_date_time],'') as [f_msc_new_date_time],
NULLIF([f_order_type_code],'') as [f_order_type_code],
NULLIF([f_part_nbr],'') as [f_part_nbr],
NULLIF([f_part_separation_name],'') as [f_part_separation_name],
NULLIF([f_pod_date_time],'') as [f_pod_date_time],
NULLIF([f_pod_timezone_code],'') as [f_pod_timezone_code],
NULLIF([f_service_type_code],'') as [f_service_type_code],
NULLIF([f_source_location_code],'') as [f_source_location_code],
NULLIF([f_ticket_closed_date_time],'') as [f_ticket_closed_date_time],
NULLIF([f_ticket_entry_date_time],'') as [f_ticket_entry_date_time],
NULLIF([f_transaction_nbr],'') as [f_transaction_nbr],
NULLIF([f_wo_nbr],'') as [f_wo_nbr],
NULLIF([f_sr_nbr],'') as [f_sr_nbr],
NULLIF([f_task_nbr],'') as [f_task_nbr],
NULLIF([f_avail_distance],'') as [f_avail_distance],
NULLIF([f_status_hist_11i_process_time],'') as [f_status_hist_11i_process_time],
NULLIF([f_status_hist_11i_process_user],'') as [f_status_hist_11i_process_user],
NULLIF([f_status_hist_canceled_time],'') as [f_status_hist_canceled_time],
NULLIF([f_status_hist_canceled_user],'') as [f_status_hist_canceled_user],
NULLIF([f_status_hist_closed_time],'') as [f_status_hist_closed_time],
NULLIF([f_status_hist_closed_user],'') as [f_status_hist_closed_user],
NULLIF([f_status_hist_exceptions_time],'') as [f_status_hist_exceptions_time],
NULLIF([f_status_hist_exceptions_user],'') as [f_status_hist_exceptions_user],
NULLIF([f_status_hist_open_time],'') as [f_status_hist_open_time],
NULLIF([f_status_hist_open_user],'') as [f_status_hist_open_user],
NULLIF([f_status_hist_order_process_ti],'') as [f_status_hist_order_process_ti],
NULLIF([f_status_hist_order_process_us],'') as [f_status_hist_order_process_us],
NULLIF([f_status_hist_pending_time],'') as [f_status_hist_pending_time],
NULLIF([f_add_to_notes],'') as [f_add_to_notes],
NULLIF([f_addl_deliv_instr],'') as [f_addl_deliv_instr],
NULLIF([f_address],'') as [f_address],
NULLIF([f_agent],'') as [f_agent],
NULLIF([f_agent_name],'') as [f_agent_name],
NULLIF([f_apjn],'') as [f_apjn],
NULLIF([f_approved],'') as [f_approved],
NULLIF([f_bin],'') as [f_bin],
NULLIF([f_canceled_reason],'') as [f_canceled_reason],
NULLIF([f_carrier_priority],'') as [f_carrier_priority],
NULLIF([f_carrier_code],'') as [f_carrier_code],
NULLIF([f_ce],'') as [f_ce],
NULLIF([f_ce_cell_phone],'') as [f_ce_cell_phone],
NULLIF([f_ce_name],'') as [f_ce_name],
NULLIF([f_ce_order_location],'') as [f_ce_order_location],
NULLIF([f_central],'') as [f_central],
NULLIF([f_central_part],'') as [f_central_part],
NULLIF([f_city],'') as [f_city],
NULLIF([f_confirmed],'') as [f_confirmed],
NULLIF([f_contact_name],'') as [f_contact_name],
NULLIF([f_contact_name_phone],'') as [f_contact_name_phone],
NULLIF([f_courier_job_number],'') as [f_courier_job_number],
NULLIF([f_create_date],'') as [f_create_date],
NULLIF([f_ctl_qty],'') as [f_ctl_qty],
NULLIF([f_customer_name],'') as [f_customer_name],
NULLIF([f_d1_wo_customer_postal],'') as [f_d1_wo_customer_postal],
NULLIF([f_d1_wo_status],'') as [f_d1_wo_status],
NULLIF([f_deliver_to],'') as [f_deliver_to],
NULLIF([f_dest_override],'') as [f_dest_override],
NULLIF([f_dhl_eta],'') as [f_dhl_eta],
NULLIF([f_dhl_manual_monitor],'') as [f_dhl_manual_monitor],
NULLIF([f_dhl_pod],'') as [f_dhl_pod],
NULLIF([f_dhl_pod_due],'') as [f_dhl_pod_due],
NULLIF([f_dhl_pod_signature],'') as [f_dhl_pod_signature],
NULLIF([f_dhl_tracking_number],'') as [f_dhl_tracking_number],
NULLIF([f_dhl_addl_deliv_instr],'') as [f_dhl_addl_deliv_instr],
NULLIF([f_disposition_code],'') as [f_disposition_code],
NULLIF([f_distance_int],'') as [f_distance_int],
NULLIF([f_elcn],'') as [f_elcn],
NULLIF([f_es_customer_name],'') as [f_es_customer_name],
NULLIF([f_es_customer_number],'') as [f_es_customer_number],
NULLIF([f_esl],'') as [f_esl],
NULLIF([f_esl_part],'') as [f_esl_part],
NULLIF([f_esl_qty],'') as [f_esl_qty],
NULLIF([f_eta_date_time_zone],'') as [f_eta_date_time_zone],
NULLIF([f_expected_date_time],'') as [f_expected_date_time],
NULLIF([f_expected_delivery],'') as [f_expected_delivery],
NULLIF([f_fedex_bol],'') as [f_fedex_bol],
NULLIF([f_fedex_eta],'') as [f_fedex_eta],
NULLIF([f_fedex_job],'') as [f_fedex_job],
NULLIF([f_fedex_order_number],'') as [f_fedex_order_number],
NULLIF([f_fedex_pod],'') as [f_fedex_pod],
NULLIF([f_from_ce_whse],'') as [f_from_ce_whse],
NULLIF([f_incident_address],'') as [f_incident_address],
NULLIF([f_incident_address2],'') as [f_incident_address2],
NULLIF([f_incident_city],'') as [f_incident_city],
NULLIF([f_incident_postal_code],'') as [f_incident_postal_code],
NULLIF([f_incident_type],'') as [f_incident_type],
NULLIF([f_initials],'') as [f_initials],
NULLIF([f_l640_onhand],'') as [f_l640_onhand],
NULLIF([f_item_description],'') as [f_item_description],
NULLIF([f_last_updated_by],'') as [f_last_updated_by],
NULLIF([f_last_updated_date_time],'') as [f_last_updated_date_time],
NULLIF([f_lcl_flag],'') as [f_lcl_flag],
NULLIF([f_mcc],'') as [f_mcc],
NULLIF([f_maxinv],'') as [f_maxinv],
NULLIF([f_msc_reference_id],'') as [f_msc_reference_id],
NULLIF([f_msl_et_count],'') as [f_msl_et_count],
NULLIF([f_msl_eta_date_time_zone],'') as [f_msl_eta_date_time_zone],
NULLIF([f_msl_locator_code],'') as [f_msl_locator_code],
NULLIF([f_msl_req],'') as [f_msl_req],
NULLIF([f_msl_req_error],'') as [f_msl_req_error],
NULLIF([f_msl_req_status],'') as [f_msl_req_status],
NULLIF([f_ncr_region],'') as [f_ncr_region],
NULLIF([f_notify_method],'') as [f_notify_method],
NULLIF([f_operating_unit],'') as [f_operating_unit],
NULLIF([f_original_part],'') as [f_original_part],
NULLIF([f_other_esl],'') as [f_other_esl],
NULLIF([f_other_esl_part],'') as [f_other_esl_part],
NULLIF([f_other_esl_qty],'') as [f_other_esl_qty],
NULLIF([f_p000],'') as [f_p000],
NULLIF([f_part_qty],'') as [f_part_qty],
NULLIF([f_part_found],'') as [f_part_found],
NULLIF([f_part_number],'') as [f_part_number],
NULLIF([f_pickup_location],'') as [f_pickup_location],
NULLIF([f_postal_code],'') as [f_postal_code],
NULLIF([f_pod_info],'') as [f_pod_info],
NULLIF([f_pod_signature],'') as [f_pod_signature],
NULLIF([f_pu_info],'') as [f_pu_info],
NULLIF([f_qty1],'') as [f_qty1],
NULLIF([f_quick_look_id],'') as [f_quick_look_id],
NULLIF([f_reason],'') as [f_reason],
NULLIF([f_remedy_id],'') as [f_remedy_id],
NULLIF([f_ref_remedy_id],'') as [f_ref_remedy_id],
NULLIF([f_region],'') as [f_region],
NULLIF([f_rw_y],'') as [f_rw_y],
NULLIF([f_service_choice],'') as [f_service_choice],
NULLIF([f_sitecode],'') as [f_sitecode],
NULLIF([f_source_inv_org],'') as [f_source_inv_org],
NULLIF([f_state_province],'') as [f_state_province],
NULLIF([f_status],'') as [f_status],
NULLIF([f_submitter],'') as [f_submitter],
NULLIF([f_suspend_code],'') as [f_suspend_code],
NULLIF([f_task_ou],'') as [f_task_ou],
NULLIF([f_task_priority],'') as [f_task_priority],
NULLIF([f_transaction_type],'') as [f_transaction_type],
NULLIF([f_vip_esl],'') as [f_vip_esl],
NULLIF([f_vms_onhand],'') as [f_vms_onhand],
NULLIF([f_vip_type],'') as [f_vip_type],
NULLIF([f_d1s_create_date],'') as [f_d1s_create_date],
NULLIF([f_part_requirement_number],'') as [f_part_requirement_number],
NULLIF([f_remedyid],'') as [f_remedyid],
NULLIF([f_requisition_internal_order],'') as [f_requisition_internal_order],
NULLIF([f_short_description],'') as [f_short_description],
NULLIF([f_d1s_status],'') as [f_d1s_status],
NULLIF([f_ucc_record_id],'') as [f_ucc_record_id],
NULLIF([f_batch_nbr],'') as [f_batch_nbr],

 --@instance_id as [instance_id],
 [infa_operation_type] as [infa_operation_type],
 [infa_sortable_sequence] as [infa_sortable_sequence],
 [ingest_partition] as [ingest_partition],
 [ingest_channel] as [ingest_channel],
 [file_path] as [file_path],
 [root_path] as [root_path],
CAST(hashbytes('sha2_256',f_extract_date_time) as VARBINARY(32)) AS [hash_key]
FROM [trans_servicepart_l3_remedy].[gsl_lrt_remedy_ticket_temp]		--temp table
)
,rn as (
 SELECT *, ROW_NUMBER() OVER (PARTITION BY hash_key ORDER BY [f_extract_date_time] DESC, infa_sortable_sequence DESC)
 as _ELT_ROWNUMBERED
 FROM gen_hashkey),
data as (
 SELECT *
 FROM rn
 WHERE _ELT_ROWNUMBERED = 1
)
MERGE INTO [trans_servicepart_l3_remedy].[gsl_lrt_remedy_ticket] tgt			--main table
USING (
 SELECT *
 FROM data
) src
ON ( src.[hash_key] = tgt.[hash_key] )
WHEN MATCHED THEN
UPDATE SET
	--add own table cols below.
	tgt.[f_extract_date_time] = src.[f_extract_date_time],
tgt.[f_tran_code] = src.[f_tran_code],
tgt.[f_instance_id] = src.[f_instance_id],
tgt.[f_remedy_ticket_nbr] = src.[f_remedy_ticket_nbr],
tgt.[f_alt_ce_part_flag] = src.[f_alt_ce_part_flag],
tgt.[f_bill_of_lading_desc] = src.[f_bill_of_lading_desc],
tgt.[f_branch_code] = src.[f_branch_code],
tgt.[f_carrier_name] = src.[f_carrier_name],
tgt.[f_ce_part_flag] = src.[f_ce_part_flag],
tgt.[f_csr_code] = src.[f_csr_code],
tgt.[f_csr_warehouse_code] = src.[f_csr_warehouse_code],
tgt.[f_part_source_loc_dist] = src.[f_part_source_loc_dist],
tgt.[f_closest_invtry_loc_name] = src.[f_closest_invtry_loc_name],
tgt.[f_country_code] = src.[f_country_code],
tgt.[f_delivery_method_code] = src.[f_delivery_method_code],
tgt.[f_msc_carrier_date_time] = src.[f_msc_carrier_date_time],
tgt.[f_msc_new_date_time] = src.[f_msc_new_date_time],
tgt.[f_order_type_code] = src.[f_order_type_code],
tgt.[f_part_nbr] = src.[f_part_nbr],
tgt.[f_part_separation_name] = src.[f_part_separation_name],
tgt.[f_pod_date_time] = src.[f_pod_date_time],
tgt.[f_pod_timezone_code] = src.[f_pod_timezone_code],
tgt.[f_service_type_code] = src.[f_service_type_code],
tgt.[f_source_location_code] = src.[f_source_location_code],
tgt.[f_ticket_closed_date_time] = src.[f_ticket_closed_date_time],
tgt.[f_ticket_entry_date_time] = src.[f_ticket_entry_date_time],
tgt.[f_transaction_nbr] = src.[f_transaction_nbr],
tgt.[f_wo_nbr] = src.[f_wo_nbr],
tgt.[f_sr_nbr] = src.[f_sr_nbr],
tgt.[f_task_nbr] = src.[f_task_nbr],
tgt.[f_avail_distance] = src.[f_avail_distance],
tgt.[f_status_hist_11i_process_time] = src.[f_status_hist_11i_process_time],
tgt.[f_status_hist_11i_process_user] = src.[f_status_hist_11i_process_user],
tgt.[f_status_hist_canceled_time] = src.[f_status_hist_canceled_time],
tgt.[f_status_hist_canceled_user] = src.[f_status_hist_canceled_user],
tgt.[f_status_hist_closed_time] = src.[f_status_hist_closed_time],
tgt.[f_status_hist_closed_user] = src.[f_status_hist_closed_user],
tgt.[f_status_hist_exceptions_time] = src.[f_status_hist_exceptions_time],
tgt.[f_status_hist_exceptions_user] = src.[f_status_hist_exceptions_user],
tgt.[f_status_hist_open_time] = src.[f_status_hist_open_time],
tgt.[f_status_hist_open_user] = src.[f_status_hist_open_user],
tgt.[f_status_hist_order_process_ti] = src.[f_status_hist_order_process_ti],
tgt.[f_status_hist_order_process_us] = src.[f_status_hist_order_process_us],
tgt.[f_status_hist_pending_time] = src.[f_status_hist_pending_time],
tgt.[f_add_to_notes] = src.[f_add_to_notes],
tgt.[f_addl_deliv_instr] = src.[f_addl_deliv_instr],
tgt.[f_address] = src.[f_address],
tgt.[f_agent] = src.[f_agent],
tgt.[f_agent_name] = src.[f_agent_name],
tgt.[f_apjn] = src.[f_apjn],
tgt.[f_approved] = src.[f_approved],
tgt.[f_bin] = src.[f_bin],
tgt.[f_canceled_reason] = src.[f_canceled_reason],
tgt.[f_carrier_priority] = src.[f_carrier_priority],
tgt.[f_carrier_code] = src.[f_carrier_code],
tgt.[f_ce] = src.[f_ce],
tgt.[f_ce_cell_phone] = src.[f_ce_cell_phone],
tgt.[f_ce_name] = src.[f_ce_name],
tgt.[f_ce_order_location] = src.[f_ce_order_location],
tgt.[f_central] = src.[f_central],
tgt.[f_central_part] = src.[f_central_part],
tgt.[f_city] = src.[f_city],
tgt.[f_confirmed] = src.[f_confirmed],
tgt.[f_contact_name] = src.[f_contact_name],
tgt.[f_contact_name_phone] = src.[f_contact_name_phone],
tgt.[f_courier_job_number] = src.[f_courier_job_number],
tgt.[f_create_date] = src.[f_create_date],
tgt.[f_ctl_qty] = src.[f_ctl_qty],
tgt.[f_customer_name] = src.[f_customer_name],
tgt.[f_d1_wo_customer_postal] = src.[f_d1_wo_customer_postal],
tgt.[f_d1_wo_status] = src.[f_d1_wo_status],
tgt.[f_deliver_to] = src.[f_deliver_to],
tgt.[f_dest_override] = src.[f_dest_override],
tgt.[f_dhl_eta] = src.[f_dhl_eta],
tgt.[f_dhl_manual_monitor] = src.[f_dhl_manual_monitor],
tgt.[f_dhl_pod] = src.[f_dhl_pod],
tgt.[f_dhl_pod_due] = src.[f_dhl_pod_due],
tgt.[f_dhl_pod_signature] = src.[f_dhl_pod_signature],
tgt.[f_dhl_tracking_number] = src.[f_dhl_tracking_number],
tgt.[f_dhl_addl_deliv_instr] = src.[f_dhl_addl_deliv_instr],
tgt.[f_disposition_code] = src.[f_disposition_code],
tgt.[f_distance_int] = src.[f_distance_int],
tgt.[f_elcn] = src.[f_elcn],
tgt.[f_es_customer_name] = src.[f_es_customer_name],
tgt.[f_es_customer_number] = src.[f_es_customer_number],
tgt.[f_esl] = src.[f_esl],
tgt.[f_esl_part] = src.[f_esl_part],
tgt.[f_esl_qty] = src.[f_esl_qty],
tgt.[f_eta_date_time_zone] = src.[f_eta_date_time_zone],
tgt.[f_expected_date_time] = src.[f_expected_date_time],
tgt.[f_expected_delivery] = src.[f_expected_delivery],
tgt.[f_fedex_bol] = src.[f_fedex_bol],
tgt.[f_fedex_eta] = src.[f_fedex_eta],
tgt.[f_fedex_job] = src.[f_fedex_job],
tgt.[f_fedex_order_number] = src.[f_fedex_order_number],
tgt.[f_fedex_pod] = src.[f_fedex_pod],
tgt.[f_from_ce_whse] = src.[f_from_ce_whse],
tgt.[f_incident_address] = src.[f_incident_address],
tgt.[f_incident_address2] = src.[f_incident_address2],
tgt.[f_incident_city] = src.[f_incident_city],
tgt.[f_incident_postal_code] = src.[f_incident_postal_code],
tgt.[f_incident_type] = src.[f_incident_type],
tgt.[f_initials] = src.[f_initials],
tgt.[f_l640_onhand] = src.[f_l640_onhand],
tgt.[f_item_description] = src.[f_item_description],
tgt.[f_last_updated_by] = src.[f_last_updated_by],
tgt.[f_last_updated_date_time] = src.[f_last_updated_date_time],
tgt.[f_lcl_flag] = src.[f_lcl_flag],
tgt.[f_mcc] = src.[f_mcc],
tgt.[f_maxinv] = src.[f_maxinv],
tgt.[f_msc_reference_id] = src.[f_msc_reference_id],
tgt.[f_msl_et_count] = src.[f_msl_et_count],
tgt.[f_msl_eta_date_time_zone] = src.[f_msl_eta_date_time_zone],
tgt.[f_msl_locator_code] = src.[f_msl_locator_code],
tgt.[f_msl_req] = src.[f_msl_req],
tgt.[f_msl_req_error] = src.[f_msl_req_error],
tgt.[f_msl_req_status] = src.[f_msl_req_status],
tgt.[f_ncr_region] = src.[f_ncr_region],
tgt.[f_notify_method] = src.[f_notify_method],
tgt.[f_operating_unit] = src.[f_operating_unit],
tgt.[f_original_part] = src.[f_original_part],
tgt.[f_other_esl] = src.[f_other_esl],
tgt.[f_other_esl_part] = src.[f_other_esl_part],
tgt.[f_other_esl_qty] = src.[f_other_esl_qty],
tgt.[f_p000] = src.[f_p000],
tgt.[f_part_qty] = src.[f_part_qty],
tgt.[f_part_found] = src.[f_part_found],
tgt.[f_part_number] = src.[f_part_number],
tgt.[f_pickup_location] = src.[f_pickup_location],
tgt.[f_postal_code] = src.[f_postal_code],
tgt.[f_pod_info] = src.[f_pod_info],
tgt.[f_pod_signature] = src.[f_pod_signature],
tgt.[f_pu_info] = src.[f_pu_info],
tgt.[f_qty1] = src.[f_qty1],
tgt.[f_quick_look_id] = src.[f_quick_look_id],
tgt.[f_reason] = src.[f_reason],
tgt.[f_remedy_id] = src.[f_remedy_id],
tgt.[f_ref_remedy_id] = src.[f_ref_remedy_id],
tgt.[f_region] = src.[f_region],
tgt.[f_rw_y] = src.[f_rw_y],
tgt.[f_service_choice] = src.[f_service_choice],
tgt.[f_sitecode] = src.[f_sitecode],
tgt.[f_source_inv_org] = src.[f_source_inv_org],
tgt.[f_state_province] = src.[f_state_province],
tgt.[f_status] = src.[f_status],
tgt.[f_submitter] = src.[f_submitter],
tgt.[f_suspend_code] = src.[f_suspend_code],
tgt.[f_task_ou] = src.[f_task_ou],
tgt.[f_task_priority] = src.[f_task_priority],
tgt.[f_transaction_type] = src.[f_transaction_type],
tgt.[f_vip_esl] = src.[f_vip_esl],
tgt.[f_vms_onhand] = src.[f_vms_onhand],
tgt.[f_vip_type] = src.[f_vip_type],
tgt.[f_d1s_create_date] = src.[f_d1s_create_date],
tgt.[f_part_requirement_number] = src.[f_part_requirement_number],
tgt.[f_remedyid] = src.[f_remedyid],
tgt.[f_requisition_internal_order] = src.[f_requisition_internal_order],
tgt.[f_short_description] = src.[f_short_description],
tgt.[f_d1s_status] = src.[f_d1s_status],
tgt.[f_ucc_record_id] = src.[f_ucc_record_id],
tgt.[f_batch_nbr] = src.[f_batch_nbr],

	--tgt.[instance_id] = src.[instance_id],
	tgt.[ingest_partition] = src.[ingest_partition],
	tgt.[ingest_channel] = src.[ingest_channel],
	tgt.[file_path] = src.[file_path],
	tgt.[root_path] = src.[root_path],
	tgt.[trans_load_date_time_utc] = GETDATE(),
	tgt.[adle_transaction_code] = src.[infa_operation_type],
	tgt.[pipeline_name] = @pipeline_name,
	tgt.[pipeline_run_id] = @pipeline_run_id,
	tgt.[pipeline_trigger_name] = @pipeline_trigger_name,
	tgt.[pipeline_trigger_id] = @pipeline_trigger_id,
	tgt.[pipeline_trigger_type] = @pipeline_trigger_type,
	tgt.[pipeline_trigger_date_time_utc] = @pipeline_trigger_date_time_utc
	
WHEN NOT MATCHED THEN
 INSERT (
 [f_extract_date_time],
[f_tran_code],
[f_instance_id],
[f_remedy_ticket_nbr],
[f_alt_ce_part_flag],
[f_bill_of_lading_desc],
[f_branch_code],
[f_carrier_name],
[f_ce_part_flag],
[f_csr_code],
[f_csr_warehouse_code],
[f_part_source_loc_dist],
[f_closest_invtry_loc_name],
[f_country_code],
[f_delivery_method_code],
[f_msc_carrier_date_time],
[f_msc_new_date_time],
[f_order_type_code],
[f_part_nbr],
[f_part_separation_name],
[f_pod_date_time],
[f_pod_timezone_code],
[f_service_type_code],
[f_source_location_code],
[f_ticket_closed_date_time],
[f_ticket_entry_date_time],
[f_transaction_nbr],
[f_wo_nbr],
[f_sr_nbr],
[f_task_nbr],
[f_avail_distance],
[f_status_hist_11i_process_time],
[f_status_hist_11i_process_user],
[f_status_hist_canceled_time],
[f_status_hist_canceled_user],
[f_status_hist_closed_time],
[f_status_hist_closed_user],
[f_status_hist_exceptions_time],
[f_status_hist_exceptions_user],
[f_status_hist_open_time],
[f_status_hist_open_user],
[f_status_hist_order_process_ti],
[f_status_hist_order_process_us],
[f_status_hist_pending_time],
[f_add_to_notes],
[f_addl_deliv_instr],
[f_address],
[f_agent],
[f_agent_name],
[f_apjn],
[f_approved],
[f_bin],
[f_canceled_reason],
[f_carrier_priority],
[f_carrier_code],
[f_ce],
[f_ce_cell_phone],
[f_ce_name],
[f_ce_order_location],
[f_central],
[f_central_part],
[f_city],
[f_confirmed],
[f_contact_name],
[f_contact_name_phone],
[f_courier_job_number],
[f_create_date],
[f_ctl_qty],
[f_customer_name],
[f_d1_wo_customer_postal],
[f_d1_wo_status],
[f_deliver_to],
[f_dest_override],
[f_dhl_eta],
[f_dhl_manual_monitor],
[f_dhl_pod],
[f_dhl_pod_due],
[f_dhl_pod_signature],
[f_dhl_tracking_number],
[f_dhl_addl_deliv_instr],
[f_disposition_code],
[f_distance_int],
[f_elcn],
[f_es_customer_name],
[f_es_customer_number],
[f_esl],
[f_esl_part],
[f_esl_qty],
[f_eta_date_time_zone],
[f_expected_date_time],
[f_expected_delivery],
[f_fedex_bol],
[f_fedex_eta],
[f_fedex_job],
[f_fedex_order_number],
[f_fedex_pod],
[f_from_ce_whse],
[f_incident_address],
[f_incident_address2],
[f_incident_city],
[f_incident_postal_code],
[f_incident_type],
[f_initials],
[f_l640_onhand],
[f_item_description],
[f_last_updated_by],
[f_last_updated_date_time],
[f_lcl_flag],
[f_mcc],
[f_maxinv],
[f_msc_reference_id],
[f_msl_et_count],
[f_msl_eta_date_time_zone],
[f_msl_locator_code],
[f_msl_req],
[f_msl_req_error],
[f_msl_req_status],
[f_ncr_region],
[f_notify_method],
[f_operating_unit],
[f_original_part],
[f_other_esl],
[f_other_esl_part],
[f_other_esl_qty],
[f_p000],
[f_part_qty],
[f_part_found],
[f_part_number],
[f_pickup_location],
[f_postal_code],
[f_pod_info],
[f_pod_signature],
[f_pu_info],
[f_qty1],
[f_quick_look_id],
[f_reason],
[f_remedy_id],
[f_ref_remedy_id],
[f_region],
[f_rw_y],
[f_service_choice],
[f_sitecode],
[f_source_inv_org],
[f_state_province],
[f_status],
[f_submitter],
[f_suspend_code],
[f_task_ou],
[f_task_priority],
[f_transaction_type],
[f_vip_esl],
[f_vms_onhand],
[f_vip_type],
[f_d1s_create_date],
[f_part_requirement_number],
[f_remedyid],
[f_requisition_internal_order],
[f_short_description],
[f_d1s_status],
[f_ucc_record_id],
[f_batch_nbr],
	
	--[instance_id],
	[hash_key],
	[ingest_partition],
	[ingest_channel],
	[file_path],
	[root_path],
	[trans_load_date_time_utc],
	[adle_transaction_code],
	[pipeline_name],
	[pipeline_run_id],
	[pipeline_trigger_name],
	[pipeline_trigger_id],
	[pipeline_trigger_type],
	[pipeline_trigger_date_time_utc]
 )
 VALUES (
 [src].[f_extract_date_time],
[src].[f_tran_code],
[src].[f_instance_id],
[src].[f_remedy_ticket_nbr],
[src].[f_alt_ce_part_flag],
[src].[f_bill_of_lading_desc],
[src].[f_branch_code],
[src].[f_carrier_name],
[src].[f_ce_part_flag],
[src].[f_csr_code],
[src].[f_csr_warehouse_code],
[src].[f_part_source_loc_dist],
[src].[f_closest_invtry_loc_name],
[src].[f_country_code],
[src].[f_delivery_method_code],
[src].[f_msc_carrier_date_time],
[src].[f_msc_new_date_time],
[src].[f_order_type_code],
[src].[f_part_nbr],
[src].[f_part_separation_name],
[src].[f_pod_date_time],
[src].[f_pod_timezone_code],
[src].[f_service_type_code],
[src].[f_source_location_code],
[src].[f_ticket_closed_date_time],
[src].[f_ticket_entry_date_time],
[src].[f_transaction_nbr],
[src].[f_wo_nbr],
[src].[f_sr_nbr],
[src].[f_task_nbr],
[src].[f_avail_distance],
[src].[f_status_hist_11i_process_time],
[src].[f_status_hist_11i_process_user],
[src].[f_status_hist_canceled_time],
[src].[f_status_hist_canceled_user],
[src].[f_status_hist_closed_time],
[src].[f_status_hist_closed_user],
[src].[f_status_hist_exceptions_time],
[src].[f_status_hist_exceptions_user],
[src].[f_status_hist_open_time],
[src].[f_status_hist_open_user],
[src].[f_status_hist_order_process_ti],
[src].[f_status_hist_order_process_us],
[src].[f_status_hist_pending_time],
[src].[f_add_to_notes],
[src].[f_addl_deliv_instr],
[src].[f_address],
[src].[f_agent],
[src].[f_agent_name],
[src].[f_apjn],
[src].[f_approved],
[src].[f_bin],
[src].[f_canceled_reason],
[src].[f_carrier_priority],
[src].[f_carrier_code],
[src].[f_ce],
[src].[f_ce_cell_phone],
[src].[f_ce_name],
[src].[f_ce_order_location],
[src].[f_central],
[src].[f_central_part],
[src].[f_city],
[src].[f_confirmed],
[src].[f_contact_name],
[src].[f_contact_name_phone],
[src].[f_courier_job_number],
[src].[f_create_date],
[src].[f_ctl_qty],
[src].[f_customer_name],
[src].[f_d1_wo_customer_postal],
[src].[f_d1_wo_status],
[src].[f_deliver_to],
[src].[f_dest_override],
[src].[f_dhl_eta],
[src].[f_dhl_manual_monitor],
[src].[f_dhl_pod],
[src].[f_dhl_pod_due],
[src].[f_dhl_pod_signature],
[src].[f_dhl_tracking_number],
[src].[f_dhl_addl_deliv_instr],
[src].[f_disposition_code],
[src].[f_distance_int],
[src].[f_elcn],
[src].[f_es_customer_name],
[src].[f_es_customer_number],
[src].[f_esl],
[src].[f_esl_part],
[src].[f_esl_qty],
[src].[f_eta_date_time_zone],
[src].[f_expected_date_time],
[src].[f_expected_delivery],
[src].[f_fedex_bol],
[src].[f_fedex_eta],
[src].[f_fedex_job],
[src].[f_fedex_order_number],
[src].[f_fedex_pod],
[src].[f_from_ce_whse],
[src].[f_incident_address],
[src].[f_incident_address2],
[src].[f_incident_city],
[src].[f_incident_postal_code],
[src].[f_incident_type],
[src].[f_initials],
[src].[f_l640_onhand],
[src].[f_item_description],
[src].[f_last_updated_by],
[src].[f_last_updated_date_time],
[src].[f_lcl_flag],
[src].[f_mcc],
[src].[f_maxinv],
[src].[f_msc_reference_id],
[src].[f_msl_et_count],
[src].[f_msl_eta_date_time_zone],
[src].[f_msl_locator_code],
[src].[f_msl_req],
[src].[f_msl_req_error],
[src].[f_msl_req_status],
[src].[f_ncr_region],
[src].[f_notify_method],
[src].[f_operating_unit],
[src].[f_original_part],
[src].[f_other_esl],
[src].[f_other_esl_part],
[src].[f_other_esl_qty],
[src].[f_p000],
[src].[f_part_qty],
[src].[f_part_found],
[src].[f_part_number],
[src].[f_pickup_location],
[src].[f_postal_code],
[src].[f_pod_info],
[src].[f_pod_signature],
[src].[f_pu_info],
[src].[f_qty1],
[src].[f_quick_look_id],
[src].[f_reason],
[src].[f_remedy_id],
[src].[f_ref_remedy_id],
[src].[f_region],
[src].[f_rw_y],
[src].[f_service_choice],
[src].[f_sitecode],
[src].[f_source_inv_org],
[src].[f_state_province],
[src].[f_status],
[src].[f_submitter],
[src].[f_suspend_code],
[src].[f_task_ou],
[src].[f_task_priority],
[src].[f_transaction_type],
[src].[f_vip_esl],
[src].[f_vms_onhand],
[src].[f_vip_type],
[src].[f_d1s_create_date],
[src].[f_part_requirement_number],
[src].[f_remedyid],
[src].[f_requisition_internal_order],
[src].[f_short_description],
[src].[f_d1s_status],
[src].[f_ucc_record_id],
[src].[f_batch_nbr],
	--[src].[instance_id],
	[src].[hash_key],
	[src].[ingest_partition],
	[src].[ingest_channel],
	[src].[file_path],
	[src].[root_path],
	GETDATE(),
	[src].[infa_operation_type],
	@pipeline_name,
	@pipeline_run_id,
	@pipeline_trigger_name,
	@pipeline_trigger_id,
	@pipeline_trigger_type,
	@pipeline_trigger_date_time_utc
 );
END TRY
BEGIN CATCH
 DECLARE @db_name VARCHAR(200),
 @schema_name VARCHAR(200),
 @error_nbr INT,
 @error_severity INT,
 @error_state INT,
 @stored_proc_name VARCHAR(200),
 @error_message VARCHAR(8000),
 @created_date_time DATETIME2
 SET @db_name=DB_NAME()
 SET @schema_name=SUBSTRING (@pipeline_name, CHARINDEX('2', @pipeline_name) + 1, LEN(@pipeline_name) - CHARINDEX('2', @pipeline_name) - 3 )
 SET @error_nbr=ERROR_NUMBER()
 SET @error_severity=ERROR_SEVERITY()
 SET @error_state=ERROR_STATE()
 SET @stored_proc_name=ERROR_PROCEDURE()
 SET @error_message=ERROR_MESSAGE()
 SET @created_date_time=GETDATE()
 EXECUTE [adle_platform_orchestration].[elt_error_log_proc]
 @db_name,
 'ERROR',
 @schema_name,
 @error_nbr,
 @error_severity,
 @error_state,
 @stored_proc_name,
 'PROC',
 @error_message,
 @created_date_time,
 @pipeline_name,
 @pipeline_run_id,
 @pipeline_trigger_name,
 @pipeline_trigger_id,
 @pipeline_trigger_type,
 @pipeline_trigger_date_time_utc
 ;
 THROW;
END CATCH
;
GO